// Alert Constants
export const SET_ALERT = "SET_ALERT";
export const REMOVE_ALERT = "REMOVE_ALERT";

// Login Constants
export const LOGIN_REQUEST = "LOGIN_REQUEST";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";

// Logout and Clearing Constants
export const LOGOUT = "LOGOUT";

// User Loading Constants
export const LOAD_USER = "LOAD_USER";
export const AUTH_ERROR = "AUTH_ERROR";

// Register Constants
export const REGISTER_REQUEST = "REGISTER_REQUEST";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAILURE = "REGISTER_FAILURE";

// Farms Constants
export const FARM_LIST_REQUEST = "FARM_LIST_REQUEST";
export const FARM_LIST_SUCCESS = "FARM_LIST_SUCCESS";
export const FARM_LIST_FAILURE = "FARM_LIST_FAILURE";

export const FARM_REQUEST = "FARM_REQUEST";
export const FARM_SUCCESS = "FARM_SUCCESS";
export const FARM_FAILURE = "FARM_FAILURE";

export const FARM_ADD_REQUEST = "FARM_ADD_REQUEST";
export const FARM_ADD_SUCCESS = "FARM_ADD_SUCCESS";
export const FARM_ADD_FAILURE = "FARM_ADD_FAILURE";

export const FARM_EDIT_REQUEST = "FARM_EDIT_REQUEST";
export const FARM_EDIT_SUCCESS = "FARM_EDIT_SUCCESS";
export const FARM_EDIT_FAILURE = "FARM_EDIT_FAILURE";

export const FARM_DELETE_REQUEST = "FARM_DELETE_REQUEST";
export const FARM_DELETE_SUCCESS = "FARM_DELETE_SUCCESS";
export const FARM_DELETE_FAILURE = "FARM_DELETE_FAILURE";

// Auctons Constants
export const AUCTION_LIST_REQUEST = "AUCTION_LIST_REQUEST";
export const AUCTION_LIST_SUCCESS = "AUCTION_LIST_SUCCESS";
export const AUCTION_LIST_FAILURE = "AUCTION_LIST_FAILURE";

export const AUCTION_REQUEST = "AUCTION_REQUEST";
export const AUCTION_SUCCESS = "AUCTION_SUCCESS";
export const AUCTION_FAILURE = "AUCTION_FAILURE";

export const AUCTION_ADD_REQUEST = "AUCTION_ADD_REQUEST";
export const AUCTION_ADD_SUCCESS = "AUCTION_ADD_SUCCESS";
export const AUCTION_ADD_FAILURE = "AUCTION_ADD_FAILURE";

export const AUCTION_EDIT_REQUEST = "AUCTION_EDIT_REQUEST";
export const AUCTION_EDIT_SUCCESS = "AUCTION_EDIT_SUCCESS";
export const AUCTION_EDIT_FAILURE = "AUCTION_EDIT_FAILURE";

export const AUCTION_DELETE_REQUEST = "AUCTION_DELETE_REQUEST";
export const AUCTION_DELETE_SUCCESS = "AUCTION_DELETE_SUCCESS";
export const AUCTION_DELETE_FAILURE = "AUCTION_DELETE_FAILURE";

export const AUCTION_JOIN_REQUEST = "AUCTION_JOIN_REQUEST";
export const AUCTION_JOIN_SUCCESS = "AUCTION_JOIN_SUCCESS";
export const AUCTION_JOIN_FAILURE = "AUCTION_JOIN_FAILURE";

export const AUCTION_GET_BID = "AUCTION_GET_BID";

// Order Constants
export const ORDER_LIST_REQUEST = "ORDER_LIST_REQUEST";
export const ORDER_LIST_SUCCESS = "ORDER_LIST_SUCCESS";
export const ORDER_LIST_FAILURE = "ORDER_LIST_FAILURE";

export const ORDER_REQUEST = "ORDER_REQUEST";
export const ORDER_SUCCESS = "ORDER_SUCCESS";
export const ORDER_FAILURE = "ORDER_FAILURE";
